### ISSUE TITLE
Structuring the repo

### ISSUE THREAD

**Issue by IgorTest19** [speakleash/speakleash-instruct-creator#11]
Due to the increasing number of files in the repository, it is worth considering organizing them in a different way. It would also be good to attach samples of generated instructions in json files.

Proposed examples of different repository files structure:

**1)** Directory for each instructions script and output json sample:
```
speakleash-instruct-creator/
├── amazon_massive/
│   ├── amazon_massive.py
│   └── amazon_massive_sample.json
├── legal-questions/
│   ├──  legal-questions.py
│   └──  legal-questions_sample.json
├── utils/
├── merge_files.py
├── requirements.txt
⋮
```

**2)** Different directories for scripts and examples:
```
speakleash-instruct-creator/
├── instructions_scripts/
│   ├── amazon_massive.py
│   └── legal-questions.py
├── instructions_samples/
│   ├──  amazon_massive_sample.json
│   └──  legal-questions_sample.json
├── utils/
├── merge_files.py
├── requirements.txt
⋮
```

**3)** Just add one additional directory for Json outputs:
```
speakleash-instruct-creator/
├── amazon_massive.py
├── egal-questions.py
├── instructions_samples/
│   ├──  amazon_massive_sample.json
│   └──  legal-questions_sample.json
├── utils/
├── merge_files.py
├── requirements.txt
⋮
```

A different structure would mean changes to the `merge_files.py` code in some cases. It would also be good to attach a simple tutorial how to create scripts for generating instructions (what they should contain/do). We can also consider the structure by domain/purpose etc.
Feel free to comment on these concepts and add your own suggestions.

**Comment by mglabska** [comment]
I would go for option 2.: it's clean and stores all scripts in one place, and scripts are more important parts of this repo (samples are just an addition).

**Comment by pawelkiszczak** [comment]
I would love to see option no. 2 as a final choice. Clear, well thought and easy for users to find the currently needed items.

**Comment by IgorTest19** [comment]
Second option will be implemented then.
