### ISSUE TITLE
Fix create_password.py - "litery" instead of "znaki"

### ISSUE THREAD

**Issue by jansowa** [speakleash/speakleash-instruct-creator#40]
In the "create_password.py" script, the word "characters" ("znaki") is used in the instructions, but the responses show that "letters" ("litery") are counted.

The word "characters" should be replaced with "letters".

By the way, you can try to create more diverse instructions.

**Comment by jansowa** [comment]
I'll do that one :)

**Comment by jansowa** [comment]
There are even more problems...

1. Generating invalid passwords. Sample:
```
{
    "instruct": "Wygeneruj losowe hasło składające się z 14 liter, 2 cyfr i 5 znaków specjalnych.",
    "input": "",
    "output": "'y\"!!'r{03[}3W55|&+((",
    "source_name": "password_creator",
    "source_url": "https://speakleash.org/",
    "source_description": "Instrukcje zostały wygenerowane automatycznie",
    "script_name": "create_password.py"
}
```
2. Generating invalid instructions, for example: "Stwórz hasło łatwe do zapamiętania składające się 14 liter, 2 cyfr i 5 znaków specjalnych." (without "z"). There are also some other similar problems.

I'll fix all of them.

**Comment by jansowa** [comment]
@chrisociepa suggested that ultimately these instructions might not be useful anyway, so I'm just uploading what I've already done - without fix of the bug associated with generating invalid passwords.

**Comment by IgorTest19** [comment]
Changes were merged. Closing issue.
