### ISSUE TITLE
New Instructions Dataset: Text Summarization

### ISSUE THREAD

**Issue by IgorTest19** [speakleash/speakleash-instruct-creator#45]
Create a new instructions dataset with texts summaries.
Simple example:
```
{
  "instruction": "Podsumuj poniższy tekst",
  "input": "Rano było dosyć chłodno, ale bardzo szybko się rozgrzało i zrobiło się naprawdę gorąco. W południe upał był niemal nie do zniesienia, szczególnie w mieście gdzie nawet lekki wiaterek nie przynosił ulgi.",
  "output": "Opis szybkiej zmiany pogody od chłodnego poranka do znacznego wzrostu temperatury w południe."
},
```

It would be beneficial to include any fields with metadata, such as:
```
"source_name": "The name of the resource used for the dataset creation, if any were used."
"source_url": "The URL of the used source datasets, if any were used."
"source_description": "A short description of the used dataset: what it is about, the purpose of creation, authors."
"script_name": "If the script generating the dataset is reusable and you want to share it with us by committing to our repository."
"status": "If the instruction has been already manually verified, you can set the status as "ok". If not, leave the field as an empty string or None."
"updated_by": "If the instruction has already been manually verified, leave your name/nickname in this field. It will help us to give thanks :)"
"id": "numeric identifier for the dataset entry"
```

Any other metadada fields including useful information are welcome to be included

**Comment by jansowa** [comment]
The following datasets are worth checking:
https://zil.ipipan.waw.pl/PolishSummariesCorpus
https://huggingface.co/datasets/allegro/summarization-allegro-articles
https://huggingface.co/datasets/WiktorS/polish-news

The first of these is not large, but is probably of the highest quality.

**Comment by jansowa** [comment]
It is also worth doing a review of previous scripts (formatting, errors, cleaning):
https://github.com/speakleash/speakleash-instruct-creator/blob/main/instructions_scripts/polish-news-summarization.py
https://github.com/speakleash/speakleash-instruct-creator/blob/main/instructions_scripts/polish-summaries-corpus.py
https://github.com/speakleash/speakleash-instruct-creator/blob/main/instructions_scripts/allegro-summarization.py

**Comment by jansowa** [comment]
Several types of new datasets (listed from the most important) are worth seeking out:
1. ready-made Polish texts with summaries
2. short documents whose summaries will be created automatically
3. English-language texts with summaries, which we can translate automatically

The quality of the third solution is likely to be the lowest, hence it is not worth spending too much time on such approach.
